"""add indexing_jobs and queued status

Revision ID: 7075b3466a83
Revises: 4f66bc06f485
Create Date: 2026-07-30 20:44:42.713346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7075b3466a83'
down_revision: Union[str, Sequence[str], None] = '4f66bc06f485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Adding a member to a non-native enum is a CHECK constraint change, which
# autogenerate does not detect — it compares columns and types, not the contents
# of a constraint. Hand-written on purpose; without it, writing 'queued' fails
# at runtime with an integrity error.
_STATUSES = ('pending', 'queued', 'cloning', 'indexing', 'ready', 'failed')
_STATUSES_BEFORE = ('pending', 'cloning', 'indexing', 'ready', 'failed')


def _status_check(values: tuple[str, ...]) -> str:
    return "status IN (" + ", ".join(f"'{v}'" for v in values) + ")"


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint('project_status', 'projects', type_='check')
    op.create_check_constraint('project_status', 'projects', _status_check(_STATUSES))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='indexing_job_status', native_enum=False, create_constraint=True, length=16), server_default='queued', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('entities_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('entities_done', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexing_jobs_project_id'), 'indexing_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_indexing_jobs_run_after'), 'indexing_jobs', ['run_after'], unique=False)
    op.create_index(op.f('ix_indexing_jobs_status'), 'indexing_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexing_jobs_status'), table_name='indexing_jobs')
    op.drop_index(op.f('ix_indexing_jobs_run_after'), table_name='indexing_jobs')
    op.drop_index(op.f('ix_indexing_jobs_project_id'), table_name='indexing_jobs')
    op.drop_table('indexing_jobs')
    # ### end Alembic commands ###

    # Rows written while 'queued' was legal would fail the narrower constraint,
    # so fold them back to the state they came from.
    op.execute("UPDATE projects SET status = 'pending' WHERE status = 'queued'")
    op.drop_constraint('project_status', 'projects', type_='check')
    op.create_check_constraint(
        'project_status', 'projects', _status_check(_STATUSES_BEFORE)
    )
