"""add commit sha and per-run entity marker

Revision ID: c5c470bdbffc
Revises: 7075b3466a83
Create Date: 2026-07-31 10:02:07.490820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c470bdbffc'
down_revision: Union[str, Sequence[str], None] = '7075b3466a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Both columns are nullable and need no backfill.

    `entities.last_seen_run` is NULL on every pre-existing row, which reads as
    "no run has seen this yet". That is harmless: the next run stamps each
    entity it keeps — including ones it skips as unchanged — before the deletion
    pass looks at the column, so nothing is dropped for having arrived before
    the marker existed.

    `projects.last_indexed_commit` stays NULL until the next successful run,
    since there is no way to know retroactively which commit an existing index
    came from. Recording a guess would be worse than recording nothing.

    No index on `last_seen_run`: the delete is always scoped by `project_id`
    first, which is already indexed.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('last_seen_run', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('last_indexed_commit', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'last_indexed_commit')
    op.drop_column('entities', 'last_seen_run')
    # ### end Alembic commands ###
