"""add full text search vector to entities

Revision ID: c76f94c9de69
Revises: c5c470bdbffc
Create Date: 2026-07-31 17:24:27.709356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c76f94c9de69'
down_revision: Union[str, Sequence[str], None] = 'c5c470bdbffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    The keyword half of hybrid search. The column is GENERATED ... STORED, so
    Postgres maintains it from qualname/description/file_path/source_code and it
    cannot drift from the row it describes — nothing in the application ever
    writes it.

    Backfill is implicit: adding a stored generated column computes it for every
    existing row, so previously indexed projects become searchable by keyword
    without a re-index. That does rewrite the table, which is worth knowing
    before running this against a large deployment.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(qualname, '')), 'A') || setweight(to_tsvector('english', coalesce(description, '')), 'B') || setweight(to_tsvector('english', coalesce(replace(file_path, '/', ' '), '')), 'C') || setweight(to_tsvector('english', coalesce(source_code, '')), 'D')", persisted=True), nullable=True))
    op.create_index('ix_entities_search_vector', 'entities', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entities_search_vector', table_name='entities', postgresql_using='gin')
    op.drop_column('entities', 'search_vector')
    # ### end Alembic commands ###
